export const LanguageOptions = [
  {
    value: 'en',
    description: 'English',
    helpUrl: 'https://help2.fracttal.com/hc/en-us',
    commentUrl: 'https://suggestions.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/en-us/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/en/checkout-pricing',
    academyUrl: '',
    referUrl: 'https://www.fracttal.com/en/refer-and-earn',
  },
  {
    value: 'es',
    description: 'Español (LaTam)',
    helpUrl: 'https://help2.fracttal.com/hc/es-es',
    commentUrl: 'https://sugerencias.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/es-es/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/es/checkout-pricing',
    academyUrl: 'https://fracttal.teachable.com',
    referUrl: 'https://www.fracttal.com/es/refiere-y-gana',
  },
  {
    value: 'es-es',
    description: 'Español',
    helpUrl: 'https://help2.fracttal.com/hc/es-es',
    commentUrl: 'https://sugerencias.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/es-es/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/es/checkout-pricing',
    academyUrl: 'https://fracttal.teachable.com',
    referUrl: 'https://www.fracttal.com/es/refiere-y-gana',
  },
  {
    value: 'pt-br',
    description: 'Português (BR)',
    helpUrl: 'https://help2.fracttal.com/hc/pt-br',
    commentUrl: 'https://sugestoes.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/pt-br/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/pt-br/checkout-pricing',
    academyUrl: 'https://fracttal-br.teachable.com/',
    referUrl: 'https://www.fracttal.com/pt-br/indicacoes',
  },
  {
    value: 'pt',
    description: 'Português (EU)',
    helpUrl: 'https://help2.fracttal.com/hc/pt-pt',
    commentUrl: 'https://sugestoes.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/pt-pt/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/pt-br/checkout-pricing',
    academyUrl: 'https://fracttal-br.teachable.com/',
    referUrl: 'https://www.fracttal.com/pt-pt/indique-e-ganhe',
  },
  {
    value: 'fr',
    description: 'Français',
    helpUrl: 'https://help2.fracttal.com/hc/fr',
    commentUrl: 'https://suggestions.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/en-us/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/en/checkout-pricing',
    academyUrl: '',
    referUrl: 'https://www.fracttal.com/en/refer-and-earn',
  },
  {
    value: 'gl',
    description: 'Galego',
    helpUrl: 'https://help2.fracttal.com/hc/en-us',
    commentUrl: 'https://sugerencias.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/en-us/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/es/checkout-pricing',
    academyUrl: 'https://fracttal.teachable.com',
    referUrl: 'https://www.fracttal.com/en/refer-and-earn',
  },
  {
    value: 'ca',
    description: 'Català',
    helpUrl: 'https://help2.fracttal.com/hc/en-us',
    commentUrl: 'https://sugerencias.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/en-us/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/es/checkout-pricing',
    academyUrl: 'https://fracttal.teachable.com',
    referUrl: 'https://www.fracttal.com/en/refer-and-earn',
  },
  {
    value: 'eu',
    description: 'Euskera',
    helpUrl: 'https://help2.fracttal.com/hc/en-us',
    commentUrl: 'https://sugerencias.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/pt-br/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/es/checkout-pricing',
    academyUrl: 'https://fracttal.teachable.com',
    referUrl: 'https://www.fracttal.com/en/refer-and-earn',
  },
  {
    value: 'it',
    description: 'Italiano',
    helpUrl: 'https://help2.fracttal.com/hc/en-us',
    commentUrl: 'https://suggestions.fracttal.com/',
    supportUrl: 'https://fracttales.zendesk.com/hc/en-us/requests/new',
    upgradeCommunity: 'https://www.fracttal.com/en/checkout-pricing',
    academyUrl: '',
    referUrl: 'https://www.fracttal.com/en/refer-and-earn',
  },
] as const;

export default LanguageOptions;
