name: 'Transfer to/from S3'
description: 'Transfer to/from S3 bucket'
author: 'Edwin Montoya <edwin.montoya@fracttal.com>'
inputs:
  source:
    description: 'S3 URL'
    required: true
    default: s3://fracttal-one-eu-dev/default/
  destination:
    description: 'Folder to upload'
    required: true
runs:
  using: "composite"
  steps:
  - name: "Upload file to S3 default"
    shell: bash
    run: |-
      aws s3 sync ${{ inputs.source}} ${{ inputs.destination }} \
      --acl public-read \
      --cache-control "max-age=86400"
