name: Deploy Android

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      bucket:
        required: true
        type: string
      env:
        required: false
        type: string
    secrets:
      DEPLOY_KEY_FRACTTAL_CORE:
        required: true
      DEPLOY_KEY_PRINT_PACKAGE:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_PASSWORD:
        required: true
jobs:
  build-deploy-android:
    runs-on: ${{ inputs.os }}
    environment: ${{ inputs.env }}
    env:
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_PASSWORD: ${{ secrets.ANDROID_PASSWORD }}
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_TAG: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.180.1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Install fastlane
      shell: bash
      run: cd android/ && bundle install && bundle update fastlane
    - name: Assemble release
      shell: bash
      run: cd android/ && bundle exec fastlane release